added page inventor/sealed
EchoMTG/website pull request #18
Opened 2022-05-12 19:54 UTC by shishir0019

2022-05-12 19:58 UTC, shishir0019 commented
![Screenshot 2022-05-13 at 1 56 09 AM](https://user-images.githubusercontent.com/19463120/168157915-46ab0ec5-ee63-47d5-9bb5-daa64c185d25.png)

2022-05-12 20:02 UTC, ardeay requested changes
Please change the top level directory of this file to `inventory`, so its `pages/inventory/sealed.vue`

2022-05-12 20:05 UTC, ardeay commented
The global search component is here https://github.com/EchoMTG/website/blob/main/components/GlobalSearch.vue

2022-05-12 20:07 UTC, ardeay commented
You can see an example of global search being imported here https://github.com/EchoMTG/website/blob/a09029bc01e1063b60e70fe54842ab7a89e2f6d7/components/NavBar.vue#L152

2022-05-12 20:15 UTC, ardeay commented on pages/inventor/sealed.vue
> +                            <input class="adjust-box input is-small acquired-date-input" type="date"  data-call="inventory/adjust_date/" v-bind:value="item.date_acquired_html"/>
```$(document).on("change",".adjust-box",function(e){
		var url = "/api/"+$(this).attr('data-call')+"id="+$(this).closest('tr,li,div,article').attr('data-id')+'&value='+$(this).val().replace(/\//g,'-');
		$.ajax(url);
	});```

2022-05-12 20:17 UTC, ardeay commented on pages/inventor/sealed.vue
> +                            <input class="adjust-box input is-small acquired-date-input" type="date"  data-call="inventory/adjust_date/" v-bind:value="item.date_acquired_html"/>
have it call a new function on the component that hits this endpoint

`/api/inventory/adjust_date/?id=[row_id]&value=[date]`

2022-05-13 12:10 UTC, ardeay requested changes
![image](https://user-images.githubusercontent.com/729972/168280268-70362b11-bdc4-4c84-9061-e4c3a810e471.png)

2022-05-13 12:51 UTC, ardeay approved these changes

2022-05-13 12:51 UTC, ardeay commented on pages/inventory/sealed.vue
> +      let url = `${process.env.API_DOMAIN}/inventory/adjust/id=${id}&adjusted_price=${value}&auth=${token}`;
Remove the first forward slash from the string `/inventory/....` because the request is making a bad url 
<img width="113" alt="image" src="https://user-images.githubusercontent.com/729972/168285133-3532963c-da71-4458-af4c-efb9aede61fe.png">

2022-05-13 12:51 UTC, merged